Repository JinraeKim/FTCTests.jl, pull requests merged in 2021-12, with the labels that each got.

#11 Fault scenarios
  src/run_sim.jl
  test/run_multiple_sim.jl
Labels: enhancement

#14 Change log dir structure
  src/run_sim.jl
  test/run_multiple_sim.jl
Labels: enhancement

#13 CI settings
  .github/workflows/CI.yml
  README.md
  main/run_multiple_sim.jl
  src/run_sim.jl
  test/run_sim.jl
  test/runtests.jl
Labels: enhancement

#17 CI fix branch name
  .github/workflows/CI.yml
  test/run_sim.jl
Labels: bug

#5 Compute recovery rate
  main/compute_recovery_rate.jl
  src/FTCTests.jl
  src/evaluate.jl
  test/evaluate.jl
  test/runtests.jl
Labels: enhancement

#15 Evaluate wrt fault
  main/compute_recovery_rate.jl
  src/FTCTests.jl
  src/fault_info.jl
Labels: enhancement

#20 Change the order of manoeuvre and method
  main/run_multiple_sim.jl
Labels: bug

#23 Add delay to df
  main/compute_recovery_rate.jl
  main/run_multiple_sim.jl
Labels: bug

#24 Update README
  README.md
Labels: documentation

#26 Change the fault time
  main/run_multiple_sim.jl
Labels: bug

#28 시뮬레이션이 멈추는 현상 방지 (loss of height 에서 강제 종료)
  main/run_multiple_sim.jl
  src/run_sim.jl
  test/run_sim.jl
Labels: bug, enhancement

#29 fix #28
  src/run_sim.jl
Labels: bug

#27 Add simulation info to dataframe
  main/compute_recovery_rate.jl
  main/run_multiple_sim.jl
Labels: enhancement

#38 Fix a bug for initial condition overwritting
  main/run_multiple_sim.jl
Labels: bug

#35 Fix a little bug
  main/compute_recovery_rate.jl
Labels: bug

#36 Integrate two manoeuvre
  main/run_multiple_sim.jl
Labels: enhancement

#41 FDI delay에 따라 초기조건이 변화하지 않도록 시뮬레이션 수정
  main/run_multiple_sim.jl
  src/run_sim.jl
Labels: bug
